dyte-io/docs

- static/api/v1.yaml
Add the maxSeconds param in the startRecording endpoint
[CORE-218]
Closes #1
[CORE-218]: https://dyte-io.atlassian.net/browse/CORE-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(recording): Add maxSeconds param in startRecording

- react-ui-kit_versioned_docs/version-0.2/installation.mdx
Fix yarn installation command for react-ui-kit
The command `yarn @dytesdk/react-ui-kit @dytesdk/react-web-core` missing `add` command inside React ui kit installation page.
Closes #1
> fix(docs): Fix yarn installation command in react UI kit installation.mdx

- static/api/v2.yaml
> feat: Added filters paramter in /sessions/:sessionId/participants/:participantId endpoint

- docs/ui-kit/basics/atomic-design.mdx
I noticed a typo while reading. Also, I had never heard of Atomic Design. I figured a link would be helpful.
> docs: fix typo & add Atomic Design blog post link

- tailwind.config.cjs
Disable default container styling in tailwind to avoid conflict with docusaurus' `.container` styling.
> fix: disable container styling in tailwind

- docs/web-core/local-user/introduction.mdx
Fixing the descriptions for `videoTrack` and `rawVideoTrack` for the web core local user properties.
> Fixing the descriptions for videoTrack and rawVideoTrack.

- docs/guides/capabilities/webhooks/webhook-events.mdx
Removed trailing comma in json.
NA
> fix: invalid json

- docs/guides/livestream/livestream-overview.mdx
Changed "https://docs.dyte.io/guides/capabilities/livestreaming-other-platforms" to "https://docs.dyte.io/guides/capabilities/misc/livestreaming-other-platforms"  Earlier link takes you to the right page if you open a new tab and to "page not found" if you click on the same tab.
Closes #1
> fix: added correct link for restream feature

- docs/guides/capabilities/ai/meeting-transcription.mdx
- docs/guides/capabilities/audio/transcriptions.mdx
Added web-core docs in transcript
Closes #1
> fix: added web-core spec in transcript

- docs/android-core/local-user/introduction.mdx
- docs/flutter-core/local-user/introduction.mdx
- docs/guides/capabilities/screensharing/enabling.mdx
- docs/ios-core/local-user/introduction.mdx
- docs/ios-core/local-user/screen-share-guide.mdx
> docs: screenshare docs for android, iOS and flutter

- docs/guides/capabilities/customize-ui/add-button-control-bar.mdx
- docs/react-ui-kit/customizations/custom-iconpack.mdx
- docs/react-ui-kit/customizations/custom-locale.mdx
- docs/react-ui-kit/using-hooks.mdx
- docs/rn-ui-kit/using-hooks.mdx
- src/theme/Playground/index.jsx
- static/release-notes/react-web-core.json
Rename all instances of `initClient ` to `initMeeting`
> fix(web): initClient / initMeeting ambiguity

- static/api/v2.yaml
Add some info around only allowing "default" key in layer config.
Closes #1
> fix: add desc about default key

- docs/angular-ui-kit/design-system.mdx
Noticed a tiny issue in the docs where a JS object was separating values with `;` instead of `,`.
> docs: Update semis to commas in JS code snippet

- src/pages/index.jsx
Added 'upto' before $30,000 in header
> header copy change

- docs/guides/migration/twilio/concepts-twilio-vs-dyte.mdx
- docs/guides/migration/twilio/feature-comparison.mdx
- docs/react-ui-kit/introduction.mdx
- src/css/custom.css
Added new section on/guides/migration/twilio/concepts-twilio-vs-dyte page
and on /guides/migration/twilio/feature-comparison page
> New section added.

- docs/guides/migration/twilio/concepts-twilio-vs-dyte.mdx
link of this button is changed
on /guides/migration/twilio/concepts-twilio-vs-dyte page
> link changed

- docs/guides/migration/twilio/concepts-twilio-vs-dyte.mdx
- docs/guides/migration/twilio/feature-comparison.mdx
- src/css/custom.css
style changes on /guides/migration/twilio/concepts-twilio-vs-dyte 
and 
/guides/migration/twilio/feature-comparison
pages
> style changes

- docs/flutter-core/chat/introduction.mdx
- docs/flutter-core/chat/sending-a-chat-message.mdx
- docs/flutter-core/host-actions.mdx
- docs/flutter-core/local-user/introduction.mdx
- docs/flutter-core/participants/events.mdx
- docs/flutter-core/participants/introduction.mdx
- docs/flutter-core/participants/participant-object.mdx
- docs/flutter-core/polls/creating-a-poll.mdx
- docs/flutter-core/polls/introduction.mdx
- docs/flutter-core/polls/receiving-polls.mdx
- docs/flutter-core/room-metadata.mdx
- Introduce a dedicated page for accessing permissions and host actions.
- Shift `broadcastMessage` API from localUser to participants section.
- Fix chat pages.
- Clubbed create & vote poll page.
- Separated poll updates page.
- Minor typo fixes.
> docs: refactor flutter_core docs

- docs/guides/capabilities/recording/stop-recording.mdx
Updates the Stop Recording API url to "https://docs.dyte.io/api?v=v2#/operations/pause_resume_stop_recording".
Also improves the the "Automatic Stop (maxSeconds elapsed)" point.
> fix(guides-recording): update the Stop Recording API url

- src/components/homepage/ResourcesSection.tsx
- src/css/custom.css
**Resolved this layout bug in mobile breakpoint.**
changed to 👇
> Layout fix

- docs/android-core-new/recording.mdx
This PR revamps the Recording documentation in the new structure. 
Closes: MOB-1599
> [android-core] Recording doc revamp

- src/faq.yaml
Updated faqs for latest participant limits, new regions and added links to dev portal, plugin SDK, blogs.
> docs(faq): updated faqs for latest participant limits, new regions and added links to dev portal

- docs/react-web-core/reference/DyteSelf.md
- docs/web-core/reference/DyteSelf.md
Clients were unable to figure out the methods to retrieve audio/video/screenshare tracks from self. Since DyteSelfMedia is a different reference, added a note to DyteSelf to highlight the connection.
> docs(dyteself-dyteselfmedia): added linking between dyteself and dyteselfmedia

- docs/angular-ui-kit/components/dyte-network-indicator.mdx
- docs/react-ui-kit/components/dyte-network-indicator.mdx
- docs/ui-kit/components/dyte-network-indicator.mdx
Added docs for dyte-network-indicator component
> docs(network-indicator): added dyte-network-indicator docs

- docs/react-ui-kit/build-in-call-ui/_category_.json
- docs/react-ui-kit/build-in-call-ui/build-your-own/_category_.json
- docs/react-ui-kit/build-in-call-ui/build-your-own/add-custom-sidebar.mdx
- docs/react-ui-kit/build-in-call-ui/build-your-own/customize-control-bar.mdx
- docs/react-ui-kit/build-in-call-ui/build-your-own/customize-header.mdx
- docs/react-ui-kit/build-in-call-ui/build-your-own/handling-states-and-configs.mdx
- docs/react-ui-kit/build-in-call-ui/build-your-own/stage-ui-using-dyte-grid.mdx
- docs/react-ui-kit/build-in-call-ui/build-your-own/states based UI Split.mdx
- docs/react-ui-kit/build-in-call-ui/default-meeting-ui.mdx
- docs/react-ui-kit/build-pre-call-ui/_category_.json
- docs/react-ui-kit/components/_category_.json
- docs/react-ui-kit/customizations/_category_.json
- docs/react-ui-kit/design-system.mdx
- docs/react-ui-kit/display-videos.mdx
- docs/react-ui-kit/quickstart.mdx
- docs/react-ui-kit/using-hooks.mdx
Added in-call UI customisation docs.
> docs(in-call-ui): added in call ui docs

- docs/ios-core/local-user/screen-share-guide.mdx
Update the documentation for screenSharing iOS. 
Closes #1
> docs: Fix the documentation of screen share on MobileCore-iOS

- docs/android/quickstart.mdx
- docs/ios/quickstart.mdx
The Android quickstart docs had an empty, incorrect table column that broke Markdown rendering.
Current prod deployment at https://docs.dyte.io/android: 
With this PR:
N/A
> fix: remove stray table syntax

- docs/flutter-core/local-user/screen-share-iOS-guide.mdx
Modifies the iOS screenshare docs, include instructions to use `DyteSampleHandler.swift` file for Screenshare support in flutter project.
> docs: modify ios screenshare docs, include instructions to use `DyteSampleHandler.swift`

- docs/guides/capabilities/video/add-virtual-background.mdx
- docs/react-ui-kit/build-pre-call-ui/build-your-own/add-middleware.mdx
- docs/react-web-core/pre-call/3-virtual-bg.mdx
- docs/web-core/pre-call/3-virtual-bg.mdx
Updated virtual background guide to support v2 changes.
> fix(virtual-background-guide): updated virtual background guide to support v2 changes

- docs/flutter-core/quickstart.mdx
- docs/flutter/quickstart.mdx
Add background permissions info for Flutter Core and UI Kit.
> docs: added bg perms for ios

- docs/android-core/Introduction.mdx
- docs/android-core/pre-call/_category_.json
- docs/android-core/quickstart.mdx
- docs/android-core/upgrade-v2/1-introduction.mdx
- docs/android-core/upgrade-v2/2-breaking-changes-migration.mdx
- docs/android-core/upgrade-v2/_category_.json
- docs/ios-core/Introduction.mdx
- docs/ios-core/pre-call/_category_.json
- docs/ios-core/quickstart.mdx
- docs/ios-core/upgrade-v2/1-introduction.mdx
- docs/ios-core/upgrade-v2/2-breaking-changes-migration.mdx
- docs/ios-core/upgrade-v2/_category_.json
- docusaurus.config.js
> mobile-core V2 upgrade docs & migration guide

- docs/guides/capabilities/ai/meeting-transcription.mdx
- docs/guides/capabilities/audio/transcriptions.mdx
- static/api/v2.yaml
* Removed Transcriptions beta message
* added support for more languages.
* Update REST API docs for breakout room changes
> docs: removed transcriptions beta note and additional transcription languages and update rest api docs for breakout room changes 

- docs/android-core/local-user/events.mdx
- docs/android-core/local-user/introduction.mdx
- docs/android-core/local-user/manage-media-devices.mdx
- docs/android-core/local-user/manage-permissions.mdx
Update android-core local user section
Fixes MOB-1903
> docs: update android-core local user section

- docs/guides/capabilities/polls/getting_started.mdx
- docs/guides/capabilities/recording/custom-cloud-storage.mdx
- docs/guides/capabilities/recording/start-recording.mdx
- docs/guides/capabilities/webhooks/webhooks-and-events.mdx
- docs/guides/livestream/advanced/livestream-any-rtmp.mdx
- docs/guides/rest-apis/livestream-dyte-meeting.mdx
- docs/guides/rest-apis/quickstart.mdx
In a lot of places, API authorization was hardcoded to a random values and it lead to confusion. Added quickstart reference across files to make it easier for newcomers.
Closes #1
> fix(api-authorization-docs): removed hardcoded API authorization tokens, added more steps to make the token generation easier

- docs/partials/error-codes/_web_core_debug_system_error_codes.mdx
- docs/partials/error-codes/_web_core_error_codes_details.mdx
- docs/react-web-core/error-codes/error-code-zero-ten.mdx
- docs/react-web-core/error-codes/error-code.mdx
- docs/react-web-core/reference/DyteClient.md
- docs/web-core/error-codes/error-code-zero-ten.mdx
- docs/web-core/error-codes/error-code.mdx
Added Web Core Error codes & the root cause behind them along with remedies to fix them.
Closes #1
> docs(error-codes): Web Core Error Codes

- docs/guides/live-video/concepts.mdx
- docs/guides/voice-conf/concepts.mdx
In [this](https://docs.dyte.io/guides/live-video/concepts) doc, under `Components`, the last line currently says:
`Let's dive deeper into what purpose each of these components _server_.`
it should be:
`Let's dive deeper into what purpose each of these components _serve_.`
> fix: minor typo in guides/concepts

- docs/partials/_angular-quickstart.mdx
- docs/partials/_html-quickstart.mdx
- docs/partials/_react-quickstart.mdx
- src/components/homepage/HomeFooter.jsx
- src/components/homepage/SDKs.tsx
- src/snippets/sdks.html
Update stale copy referring to Chat SDK.
Closes #1
> fix: removed chat sdk references
