dyte-io/docs

.github/PULL_REQUEST_TEMPLATE.md, README.md
- Updated the repo title in README
- Updated the PR template
NA
=> docs: update README and PR template

.github/CODEOWNERS
=> docs: added codeowners file

static/api/v1.yaml
Added the url params in start recording API which allows organizations to record any URLs.
=> docs(recording): added url param in the start recording API

.github/CODEOWNERS
=> docs: fix codeowners file

.github/workflows/docsearch.yml
Run algolia docsearch on GitHub actions.
NA
=> ci(docsearch): run algolia docsearch on push to main

bin/crawl.sh
Removed `-it` from crawl.sh so that the script can run in actions.
NA
=> fix(crawl): -it option fails in CI

.github/workflows/docsearch.yml
Docsearch exits with status code 3 when docs weren't updated, but the action should not fail for this reason.
NA
=> fix: ignore docsearch docs-not-updated errors

.github/CODEOWNERS
=> fix(codeowners): updated team names in the repository

docusaurus.config.js
- Shows the "Edit this page" for all sections except the main page.
- Shows last updated metadata
None
=> feat: show `edit this page` and last edited metadata

static/api/v1.yaml
Add default values to totalMinutes in all stats api
=> fix(api): add default value to all stats api

static/api/v1.yaml
=> fix: add default value for totalMinutes to fix stoplight overflow

docs/guides/integrating-with-webhooks.mdx, docs/guides/recording-your-meetings.mdx, docsearch_config.json, docusaurus.config.js, sidebars/sidebars-docs.js, sidebars/sidebars-guides.js, src/css/tailwind.css, src/theme/Navbar/index.js
Renames the webhooks guide title.
=> fix: rename webhooks guide

src/components/APIVersionSwitcher.jsx, src/pages/api.jsx
Adds Postman collection button for v1 api.
=> feat: add postman collection button for v1 api

static/api/v1.yaml
Updated the API spec with latest one
=> docs(api-spec): updated API spec

docs/react/virtual-background.mdx, react_versioned_docs/version-0.30.x/virtual-background.mdx
Added docs for virtual background
=> docs(background): added virtual background docs

docusaurus.config.js, src/css/tailwind.css
Adds announcement banner with text
```
Coming Soon: Next generation SDKs for web and mobile
```
N/A
=> feat: add announcement for upcoming sdks

src/components/APIVersionSwitcher.jsx, src/pages/api.jsx
Fix button placement when announcement bar is shown.
=> fix(api): button placement with announcement

static/api/v2.yaml
Added GET /meetings/:meetingId/sessions in v2
=> docs: Added GET /meetings/:meetingId/sessions in v2

docs/javascript/virtual-background.mdx, javascript_versioned_docs/version-0.33.x/virtual-background.mdx, react_versioned_docs/version-0.33.x/virtual-background.mdx
Fix virtual background documentation
=> fix: virtual background docs

static/api/v1.yaml
Set API response code for validation errors to 422 from 400 to reflect backend changes
=> fix(api/v1): document validation error backend response code as 422 according to changes in backend

patches/@stoplight+elements-core+7.4.0.patch, static/api/v2.yaml
- Updated v2 api spec to add global security inputs.
- Patch packages basic auth input field names
=> feat: update v2 api spec, patch-package test-runner ui

LICENSE, docs/main/home/introduction.mdx
=> fix(content): fix docs content

docs/javascript/customize-meeting-ui.mdx, docs/react/customize-meeting-ui.mdx, docs/web-core/participants/participant-object.mdx, docs/web-core/participants/participants.mdx, src/css/api-reference.css
- fix: broken links and link color in api ref
=> fix: broken links and link color in api ref

docusaurus.config.js, plugins/posthog-plugin.cjs, src/components/SidebarMenu/styles.module.css, src/css/custom.css, src/sections.js, src/utils/posthog.js
- feat: add analytics
- fix: sections menu design update
=> feat: add analytics

.eslintignore, src/components/SidebarMenu/styles.module.css, src/components/VideoPlayer.jsx, src/css/custom.css, src/pages/api.jsx
=> fix: api v2 message, ui fixes

docusaurus.config.js
=> feat: added google analytics

docs/android-core/chat/_category_.json, docs/android-core/chat/introduction.mdx, docs/android-core/chat/receiving-chat-messages.mdx, docs/android-core/chat/sending-a-chat-message.mdx, docs/android-core/local-user/_category_.json, docs/android-core/local-user/events.mdx, docs/android-core/local-user/introduction.mdx, docs/android-core/local-user/manage-media-devices.mdx, docs/android-core/participants/_category_.json, docs/android-core/participants/events.mdx, docs/android-core/participants/introduction.mdx, docs/android-core/participants/participant-object.mdx, docs/android-core/polls/_category_.json, docs/android-core/polls/creating-a-poll.mdx, docs/android-core/polls/introduction.mdx, docs/android-core/polls/voting-on-a-poll.mdx, docs/android-core/quickstart.mdx, docs/android-core/recording.mdx, docs/android-core/room-metadata.mdx, docs/home/how-dyte-works.mdx, docusaurus.config.js, src/components/SidebarMenu/index.jsx, src/sections.js
=> feat: merge upstream

docs/web-core/reference/DyteChat.md, docs/web-core/reference/DyteClient.md, docs/web-core/reference/DyteMeta.md, docs/web-core/reference/DyteParticipant.md, docs/web-core/reference/DyteParticipantMap.md, docs/web-core/reference/DyteParticipants.md, docs/web-core/reference/DytePermissionsPreset.md, docs/web-core/reference/DytePlugin.md, docs/web-core/reference/DytePluginMap.md, docs/web-core/reference/DytePlugins.md, docs/web-core/reference/DytePolls.md, docs/web-core/reference/DyteRecording.md, docs/web-core/reference/DyteRemote.md, docs/web-core/reference/DyteSelf.md, docs/web-core/reference/DyteThemePreset.md, docs/web-core/reference/README.md, docusaurus.config.js
=> feat: update web-core references to 0.38.0

static/api/v2.yaml
=> docs: api reference changes

static/api/v2.yaml
Updated openapi spec to add GET /meetings/:meetingId/sessions endpoint
=> feat: [CORE-1375] Updated spec to add GET /meetings/:meetingId/sessions

docs/android/installation.mdx, docs/android/sample-app.mdx
Update android-ui-kit version -> 0.0.3
=> Docs android

docs/guides/integrating-with-webhooks.mdx, src/components/homepage/SDKsSection.jsx, src/css/custom.css
Small UI & Documentation fixes.
=> fix: link, ui fixes

docs/android-core/participants/events.mdx, docs/android-core/participants/participant-object.mdx
For android-core
Added pin participant docs.
Updated pagination api changes docs.
=> feat: added pin participant and pagination api changes docs

src/components/homepage/APIReferenceSection.jsx, src/components/homepage/CommunitySection.jsx, src/components/homepage/HeroSection.jsx, src/components/homepage/HomeFooter.jsx, src/components/homepage/ResourcesSection.jsx, src/components/homepage/SDKsSection.jsx, src/css/custom.css, src/pages/faq.jsx, src/pages/index.jsx, src/snippets/sdks.html
Landing page and FAQ page design changes.
=> fix: landing page and faq page design changes

docs/javascript/customize-meeting-ui.mdx, docs/react/customize-meeting-ui.mdx, src/components/homepage/SDKsSection.jsx, src/snippets/sdks.html
=> fix: broken links

docs/react-ui-kit/introduction.mdx, docs/web-core/quickstart.mdx, src/components/homepage/SDKsSection.jsx, src/snippets/sdks.html, static/_redirects
=> fix: broken links (web-core, hooks)

static/api/v2.yaml
Change `us-west-1` region to `us-east-1`
=> fix: region name in V2 API docs

docs/react-web-core/introduction.mdx, docs/react-web-core/quickstart.mdx, docs/react-web-core/release-notes.mdx, docusaurus.config.js, src/components/homepage/SDKsSection.jsx, src/sections.ts, src/snippets/sdks.html
Added React Web Core documentation
=> feat: react core sdk docs

static/api/v2.yaml
Adds `filter` query param documentation to participant details API
=> feat: participant details query params

static/api/v2.yaml
=> docs: api reference update

docs/flutter-core/participants/events.mdx, docs/guides/livestream/index.mdx, static/api/v2.yaml
- Added livestream main page
- Flutter code fixes
=> docs: livestream main page, flutter code fix

static/api/v2.yaml
=> docs: api reference fixes

docs/react-web-core/recording.mdx, docs/web-core/recording.mdx, static/api/v2.yaml, static/release-notes/react-web-core.json, static/release-notes/ui-kit.json, static/release-notes/web-core.json
Add release notes for 
- Web Core: 1.9.0
- React Web Core: 1.25.0
- UI Kit : 1.46.0
=> feat: add release docs for web-core(1.9.0) and ui-kit(1.46.0)

bin/ui-kit/component-docs.cjs, docs/angular-ui-kit/components/dyte-breakout-room-grid.mdx, docs/angular-ui-kit/components/dyte-breakout-room-manager.mdx, docs/angular-ui-kit/components/dyte-breakout-room-tile.mdx, docs/angular-ui-kit/components/dyte-breakout-rooms-manager.mdx, docs/angular-ui-kit/components/dyte-breakout-rooms-toggle.mdx, docs/react-ui-kit/components/dyte-breakout-room-grid.mdx, docs/react-ui-kit/components/dyte-breakout-room-manager.mdx, docs/react-ui-kit/components/dyte-breakout-room-tile.mdx, docs/react-ui-kit/components/dyte-breakout-rooms-manager.mdx, docs/react-ui-kit/components/dyte-breakout-rooms-toggle.mdx, docs/react-ui-kit/components/dyte-broadcast-message-modal.mdx, docs/ui-kit/components/dyte-breakout-room-grid.mdx, docs/ui-kit/components/dyte-breakout-room-manager.mdx, docs/ui-kit/components/dyte-breakout-room-tile.mdx, docs/ui-kit/components/dyte-breakout-rooms-manager.mdx, docs/ui-kit/components/dyte-breakout-rooms-toggle.mdx
Exclude breakout room component documentation.
=> docs: exclude breakout room components

docs/react-ui-kit/basics/integrate.mdx, src/pages/faq.jsx
- UI Kit integrate doc update
- FAQ pill design fix
=> fix: ui-kit doc update, faq pill design

src/theme/SearchBar/index.jsx
=> fix: searchbar ui updates

package-lock.json, package.json, src/css/custom.css, src/theme/Footer/Logo/index.jsx, src/theme/SearchBar/index.jsx
- Searchbar overlay colors updated
- Upgraded ai package
=> fix: searchbar overlay colors and upgrade package

src/components/homepage/CommunitySection.jsx, src/components/homepage/HomeFooter.jsx
Changed "Your Safety is utmost important to us" to "Your safety is of utmost importance to us"
Here's what it looks like now:
Closes #212
=> docs(grammar): fix grammatical error in footer

docusaurus.config.js
- The sidebar will now only showcase the category the user clicks on, rest all other categories will be collapsed automatically.
Closes #214
=> feat: Auto Collapsible Sidebar Functionality

docs/guides/capabilities/ai/_category_.json, docs/guides/capabilities/ai/index.mdx, docs/guides/capabilities/ai/meeting-transcription.mdx, docs/guides/capabilities/breakoutroom/_category_.json
This PR adds the documentation for meeting AI - transcription.
NA
=> feat: added docs for meeting transcripts

docs/guides/capabilities/ai/meeting-transcription.mdx
Added a banner indicating that meeting transcription is still in beta.
Closes NA
=> fix: added beta banner

docs/guides/capabilities/ai/meeting-transcription.mdx
Add an alpha tag on meeting AI
NA
=> fix: added alpha tag on meeting AI

docs/react-web-core/reference/DyteMeta.md, docs/react-web-core/reference/DyteParticipant.md, docs/react-web-core/reference/DytePlugin.md, docs/react-web-core/reference/DyteStage.md, docs/rn-core/reference/DyteStage.md, docs/web-core/reference/DyteMeta.md, docs/web-core/reference/DyteParticipant.md, docs/web-core/reference/DytePlugin.md, docs/web-core/reference/DyteStage.md
Resolves grammar issues and typos from docs
-
=> docs: fix grammar issues and typos

docs/guides/capabilities/ai/meeting-transcription.mdx
Update the CSV format for transcripts.
NA
=> fix: update docs for csv

docs/react-web-core/participants/pip.mdx
=> fix: typo for pip methods

src/components/homepage/HomeFooter.jsx, src/pages/index.jsx
=> banner text and link changed

src/components/homepage/HomeFooter.jsx
=> added few links in footer

docs/android-core/local-user/introduction.mdx, docs/android-core/local-user/manage-permissions.mdx, docs/android-core/participants/introduction.mdx, docs/android-core/participants/participant-object.mdx, docs/android-core/quickstart.mdx
=> docs: updated android core docs

docs/android-core/quickstart.mdx, docs/android/quickstart.mdx
fixes quickstart for android and android ui kit
=> Fix android quickstart docs

docs/guides/capabilities/video/picture-in-picture.mdx
=> docs: update picture-in-picture.mdx

docs/ios-core/quickstart.mdx, docs/ios/quickstart.mdx
added SPM source in iOS installation steps
=> fix: spm docs

static/api/v2.yaml
Adds new experimental track based recording API spec.
N/A
=> feat(recording): add start track recording API

static/release-notes/react-web-core.json, static/release-notes/ui-kit.json, static/release-notes/web-core.json
Updated release notes for
```
"@dytesdk/react-ui-kit": "1.63.0"
"@dytesdk/react-web-core": "1.35.19"
"@dytesdk/web-core": "1.26.0"
```
=> docs: update release notes

docs/plugin-sdk/setup/manage.mdx
=> docs: update manage.mdx

docs/ios/components/_category_.json, docs/ios/components/dyte-avatar.mdx, docs/ios/components/dyte-button.mdx, docs/ios/components/dyte-camera-toggle.mdx, docs/ios/components/dyte-chat.mdx, docs/ios/components/dyte-clock.mdx, docs/ios/components/dyte-controlbar-button.mdx, docs/ios/components/dyte-grid-pagination.mdx, docs/ios/components/dyte-grid.mdx, docs/ios/components/dyte-join-stage.mdx, docs/ios/components/dyte-leave-meeting.mdx, docs/ios/components/dyte-meeting-title.mdx, docs/ios/components/dyte-meeting.mdx, docs/ios/components/dyte-mic-toggle.mdx, docs/ios/components/dyte-more-toggle.mdx, docs/ios/components/dyte-name-tag.mdx, docs/ios/components/dyte-participant-count.mdx, docs/ios/components/dyte-participants.mdx, docs/ios/components/dyte-plugins.mdx, docs/ios/components/dyte-poll-form.mdx, docs/ios/components/dyte-polls.mdx, docs/ios/components/dyte-recording-indicator.mdx, docs/ios/components/dyte-settings.mdx, docs/ios/components/dyte-setup-screen.mdx, docs/ios/components/dyte-webinar-stage-toggle.mdx
=> chore: added initial uikit components docs

docs/android/sample-app.mdx, docs/flutter-core/quickstart.mdx, docs/flutter/quickstart.mdx, docs/ios/quickstart.mdx, docs/partials/_android-quickstart.mdx, docs/partials/_flutter-quickstart.mdx
fixes sample app links for mobile samples.
=> fix: fixes mobile sample app links

static/release-notes/ui-kit.json
Updating release notes for ui-kit
=> docs: update ui-kit release notes

docs/react-web-core/error-codes/error-code-zero-ten.mdx, docs/web-core/error-codes/error-code-zero-ten.mdx
removes random code from web-core error-codes page
=> docs: removed random code from error codes page on web-core

docusaurus.config.js, package.json
Query param added to support url to open the desired tab on Contact page.
=> support link modified

docs/guides/migration/twilio/concepts-twilio-vs-dyte.mdx, src/components/homepage/HomeFooter.jsx
=> Footer dropdowns

docs/android/quickstart.mdx
- Updated in page links for objectives and their details
- Updated description for the DyteMeetingInfoV2 config fields
=> docs: add hyperlinks in android uikit quickstart

static/api/v2.yaml
=> feat: added export_file in recording config

docs/rn-ui-kit/quickstart.mdx
- Updated Quickstart Docs for React Native
- Added Expo Installation instructions
=> fix: updated react native quickstart docs

docs/guides/capabilities/webhooks/webhook-events.mdx
=> fix: webhooks docs missing fields & tabs

src/pages/api.jsx, static/api/v2.yaml
added title & description tags on this page -> /api/#/
=> added title & description tags

docs/ios-core/quickstart.mdx
- updated baseUrl & explained meetingInfo params
- added links for steps
- used tabs for dependencies
=> chore: refactor ios core docs

docs/angular-ui-kit/quickstart.mdx, docs/react-ui-kit/build-pre-call-ui/build-your-own/add-audio-video-preview.mdx, docs/react-ui-kit/build-pre-call-ui/build-your-own/edit-user-name.mdx, docs/react-ui-kit/build-pre-call-ui/build-your-own/initial-code-skeleton.mdx, package-lock.json, package.json, src/components/CodeRunner/CodeRunner.jsx, src/components/CodeRunner/ReactBoilerplate.ts, src/css/custom.css
- Angular live preview is still WIP, due to Angular UI Kit's requirement of setting `allowSyntheticDefaultImports`:true
=> feat: add sandpack code runner

docs/react-ui-kit/components/dyte-audio-visualizer.mdx
https://dyte.slack.com/archives/C06H7K1CA00/p1711632923527259
Closes #1
=> fix: use correct prop

docs/ios/quickstart.mdx
I have added explanation to existing steps. Add further segregation to steps to clearly show intention of each steps.
Closes #1
=> docs: add link internally to guide steps, and add explanation to steps. MOB-1512

static/release-notes/android-core.json, static/release-notes/android-ui-kit.json, static/release-notes/iOS-core.json
- android-core release notes
- iOS-core release notes
- android-ui-kit release notes
=> Mobile core release notes

static/release-notes/android-core.json, static/release-notes/android-ui-kit.json, static/release-notes/iOS-core.json, static/release-notes/iOS-ui-kit.json
- android-core 1.34.4
- android-ui-kit 1.17.3
- iOS-core 1.34.4
- iOS-ui-kit 0.6.6
=> docs: android-core, android-ui-kit, iOS-core & iOS-ui-kit

docs/android-core/local-user/introduction.mdx
Adds notes for explaining nuances of adding media projection permission for screen share in manifest
=> docs: added note for media projection permission

static/release-notes/flutter-core.json, static/release-notes/flutter-ui-kit.json
Fixes: [[MOB-1777](https://linear.app/dyte/issue/MOB-1777/docs-update-release-notes-of-flutter-core-till-june24)] [[MOB-1778](https://linear.app/dyte/issue/MOB-1778/docs-update-release-notes-of-flutter-uikit-till-june24)]
=> docs: release notes for flutter_core and flutter uikit [MOB-1777] [MOB-1778]

static/release-notes/flutter-core.json, static/release-notes/flutter-ui-kit.json
=> docs: add release notes for dyte_core 0.4.0, dyte_uikit 0.7.7

docs/flutter/meeting-locale.mdx
This PR contains steps to support custom locale in Flutter UI Kit.
=> docs: support custom locale to your flutter ui kit [MOB-1805]

docs/flutter/quickstart.mdx
This PR documents skipping setup screen on prebuilt flutter ui-kit.
=> docs: add doc for skipping setup screen in flutter ui-kit

docs/guides/capabilities/ai/index.mdx, docs/guides/capabilities/ai/meeting-summary.mdx, docs/guides/capabilities/ai/meeting-transcription.mdx, docs/guides/capabilities/webhooks/webhook-events.mdx, static/api/v2.yaml
* Added meeting summary guide.
* Docs for ai config.
* Added generate summary REST API.
* Revamped meeting transcription guide.
* Added `meeting.summary` webhook event in webhook guide.
=> docs: ai config and summary guide

docs/rn-ui-kit/using-hooks.mdx
It solves a typo error on the `using-hook.mdx`
=> docs: typo on using hook example

src/components/homepage/HeroSection.tsx, src/components/homepage/PhHelloBar.jsx, src/css/custom.css, src/pages/index.jsx
=> Added a banner for PH launch

src/components/homepage/PhHelloBar.jsx, src/pages/index.jsx, static/release-notes/react-web-core.json, static/release-notes/web-core.json
=> Ph banner txt update

src/components/homepage/PhHelloBar.jsx
=> updated banner text

src/components/homepage/PhHelloBar.jsx
=> removed cat image from banner

static/release-notes/react-web-core.json, static/release-notes/web-core.json
Added release notes for web-core 2.1.8 and 2.1.9 release.
Closes #1
=> chore(release-notes): update release notes for web-core 2.1.8 and 2.1.9

docs/android-core/pre-call/1-media-preview.mdx, docs/android-core/pre-call/2-handling-permissions.mdx, docs/android-core/pre-call/3-meeting-meta.mdx, docs/android-core/pre-call/4-waiting-room.mdx, docs/android-core/quickstart.mdx
Updates the quickstart and pre-call section docs for the v2 SDK
Fixes MOB-1899
Fixes MOB-1901
=> docs: start updating android-core docs for v2

docs/android-core/participants/events.mdx, docs/android-core/participants/participant-object.mdx, docs/android-core/participants/remote-participants.mdx, docs/android-core/participants/waitlisted-participants.mdx, docs/android-core/pre-call/4-waiting-room.mdx
=> docs: update remote participants section for mobile-core v2

static/release-notes/react-web-core.json, static/release-notes/ui-kit.json, static/release-notes/web-core.json
=> docs(release-notes): adding release notes for web-core 2.2.0 & ui-kit 2.1.3

docs/ios-core/chat/introduction.mdx, docs/ios-core/chat/receiving-chat-messages.mdx, docs/ios-core/chat/sending-a-chat-message.mdx, docs/ios-core/local-user/events.mdx, docs/ios-core/local-user/introduction.mdx, docs/ios-core/participants/events.mdx, docs/ios-core/participants/participant-object.mdx, docs/ios-core/participants/remote-participants.mdx, docs/ios-core/participants/waitlisted-participants.mdx, docs/ios-core/pre-call/1-media-preview.mdx, docs/ios-core/pre-call/4-waiting-room.mdx, docs/ios-core/quickstart.mdx, docs/ios-core/stage-management/1-introduction.mdx, docs/ios-core/stage-management/2-host-controls.mdx, docs/ios-core/stage-management/3-viewer-participants.mdx, docs/ios-core/upgrade-v2/1-introduction.mdx
=> docs: started updating ios-core docs for v2

static/release-notes/react-web-core.json, static/release-notes/web-core.json
Adding release notes for recent patch releases.
Closes #1
=> docs(release-notes): adding release notes of 2.4.1, 2.4.2, 2.4.3 releases

docs/guides/live-video/concepts.mdx, docs/guides/voice-conf/concepts.mdx
Some minor grammatical fixes to make for easier reading. 
https://docs.dyte.io/guides/voice-conf/concepts
https://docs.dyte.io/guides/live-video/concepts
WEB-4308
=> Docs: concepts grammar and style

src/pages/index.jsx
=> Fix: removed banner for feta

docs/ui-kit/components/dyte-simple-grid.mdx
=> docs: Fix typo in dyte-simple-grid.mdx

static/api/v2.yaml
=> Revert "fix: remove rtmp_url and url from start recording and edit preset for…"

static/api/v2.yaml
=> fix: adding back rtmp url and remove from example only

static/release-notes/react-web-core.json, static/release-notes/web-core.json
Adding release notes for new web-core releases.
Closes #1
=> docs(release-notes): adding release notes for 2.4.4 & 2.4.5
